### ISSUE TITLE
OSX Environment variables not set

### ISSUE THREAD

**Issue by rcollette** [luktom/OpenInTerminal#12]
This was working up until I set the NPM_TOKEN environment variable.   This works fine when using the standard JetBrains command for opening a terminal, but when I use OpenInTerminal it seems like the environment variables (which are set using ~/.bash_profile), does not get set before npm initialization occurs.   But when I go to the command line after the terminal opens and run `env` I do see that NPM_TOKEN has been set.

So there is some difference between the way JetBrains creates a terminal session and the way that OpenInTerminal does.

```
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:411:12)
    at parseField (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:389:7)
    at /Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:316:10)
    at /Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/npm.js:59:13)
    at process.errorHandler (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:205:32)
    at process.emit (events.js:210:5)
    at process._fatalException (internal/process/execution.js:150:25)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v12.13.0 --silent` to unset it.
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:411:12)
    at parseField (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:389:7)
    at /Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/config/core.js:316:10)
    at /Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/npm.js:59:13)
    at process.errorHandler (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/npm/lib/utils/error-handler.js:205:32)
    at process.emit (events.js:210:5)
    at process._fatalException (internal/process/execution.js:150:25)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v12.13.0 --silent` to unset it.

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
```

**Comment by rcollette** [comment]
Sorry this is actually a Webstorm issue.
